edition = "2024"

condense_wildcard_suffixes = true
fn_single_line = true
format_code_in_doc_comments = true
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
max_width = 100
struct_lit_width = 25
trailing_comma = "Never"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true